/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        rodger: ['"Rodger Bold"', '"Rodger Bold Placeholder"', 'Arial', 'sans-serif'],
        onest: ['"Onest"', '"Onest Placeholder"', 'sans-serif'],
      },
      colors: {
        ink: 'var(--wr-ink)',
        'text-muted': 'var(--wr-text-muted)',
        'text-subtle': 'var(--wr-text-subtle)',
        surface: 'var(--wr-white)',
        'bg-peach': 'var(--wr-bg-peach)',
        'bg-cyan': 'var(--wr-bg-cyan)',
        'bg-salmon': 'var(--wr-bg-salmon)',
        'bg-panel-gray': 'var(--wr-bg-panel-gray)',
        'bg-panel-light': 'var(--wr-bg-panel-light)',
        'bg-yellow': 'var(--wr-bg-yellow)',
        'accent-orange': 'var(--wr-accent-orange)',
        'accent-blue': 'var(--wr-accent-blue)',
        'accent-yellow': 'var(--wr-accent-yellow)',
        'accent-yellow-soft': 'var(--wr-accent-yellow-soft)',
        'tag-yellow': 'var(--wr-tag-yellow)',
        'cta-text': 'var(--wf-cta-conv-text)',
        'on-dark': 'var(--wf-on-dark)',
        'on-dark-muted': 'var(--wf-on-dark-muted)',
        'section-dark': 'var(--wf-section-dark-bg)',
        'hover-bg-subtle': 'var(--wf-hover-bg-subtle)',
        'feedback-error': 'var(--wf-feedback-error)',
        'feedback-error-bg': 'var(--wf-feedback-error-bg)',
        'feedback-warning': 'var(--wf-feedback-warning)',
        'feedback-warning-bg': 'var(--wf-feedback-warning-bg)',
        'feedback-success': 'var(--wf-feedback-success)',
        'feedback-success-bg': 'var(--wf-feedback-success-bg)',
        'feedback-info': 'var(--wf-feedback-info)',
        'feedback-info-bg': 'var(--wf-feedback-info-bg)',
      },
      borderRadius: {
        pill: '999px',
        20: '20px',
        16: '16px',
        12: '12px',
        8: '8px',
      },
      boxShadow: {
        badge: 'var(--wr-shadow-badge)',
        email: 'var(--wr-shadow-email)',
        'card-base': '0 8px 20px rgba(48, 33, 39, 0.06)',
        'card-hover': '0 14px 26px rgba(48, 33, 39, 0.12)',
        'nav-shell': 'var(--wf-nav-shell-shadow)',
        'nav-scrolled': 'var(--wf-nav-scrolled-shadow)',
        'footer-shell': 'var(--wf-footer-shell-shadow)',
        'tenant-form': 'var(--wf-tenant-form-shadow)',
      },
      transitionTimingFunction: {
        gentle: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        fast: '220ms',
        base: '280ms',
      },
      screens: {
        tablet: { min: '800px', max: '1399.98px' },
        desktop: '1400px',
      },
      maxWidth: {
        'container-main': '1280px',
        'container-focus': '840px',
        'container-cta': '640px',
      },
    },
  },
  plugins: [],
};
